name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  features:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        feature:
          # Library components, one by one
          - rgb
          - lnp
          # ... and used together
          - rgb,lnp
          # Cryptographic optionals
          - keygen
          - bulletproofs
          - elgamal
          # Core rust optionals
          - serde
          - tokio
          - async
          # Networking
          - url
          - websockets
          # Full LNP strength, but without Serde
          - lnp,websockets,url,tokio,async,keygen
          # Full library strength, but without Serde
          - rgb,lnp,tokio,websockets,url,async,keygen
    steps:
      - uses: actions/checkout@v2
      - name: Install linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libzmq3-dev
      - name: Install macos dependencies
        if: matrix.os == 'macos-latest'
        run: brew install pkg-config zmq
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Feature ${{ matrix.feature }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features=${{ matrix.feature }}
      - name: Defaults + ${{ matrix.feature }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features=${{ matrix.feature }}
  tor:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        feature:
          - tor
          - tor,url
    steps:
      - uses: actions/checkout@v2
      - name: Install linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libzmq3-dev libssl-dev
      - name: Install macos dependencies
        if: matrix.os == 'macos-latest'
        run: brew install pkg-config zmq
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Feature ${{ matrix.feature }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --features=${{ matrix.feature }}
      - name: Defaults + ${{ matrix.feature }}
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features=${{ matrix.feature }}
  toolchains:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        toolchain: [ nightly, beta, stable, 1.41.1 ]
    steps:
      - uses: actions/checkout@v2
      - name: Install linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libzmq3-dev libssl-dev
      - name: Install macos dependencies
        if: matrix.os == 'macos-latest'
        run: brew install pkg-config zmq
      - name: Install rust ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: All features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --all-targets --all-features
  dependency:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Install linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libzmq3-dev libssl-dev
      - name: Install macos dependencies
        if: matrix.os == 'macos-latest'
        run: brew install pkg-config zmq
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Create dependency
        run: |
          cargo new dep_test
          cp contrib/depCargo.toml dep_test/Cargo.toml
          cd dep_test
      - name: Build dependency
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      - name: Clean up
        run: |
          cd ..
          rm -rf dep_test
